# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Theo Duffaut
title: Robotics Engineer
email: duffaut.theo@gmail.com
website: https://theodfft.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  TheoDfft
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: theo-duffaut
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: <b>About Me</b>
about_profile_image: images/profile_pic.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Theo and I'm an aspiring robotics engineer. I'm passionate about new technologies, how they work and how to apply them to have an impact on the world. With a background in Mechanical Engineering, specializations in Robotics and Machine Learning and two years of industry experience with AMR deployment, I'm looking for new opportunities to grow and learn.<br><br>
  Currently pursuing a M.S in Mechatronics and Robotics at New York University. Graduating in December 2025.

content:
  - title: <b>Projects</b> # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: SCARA Drawbot
        link: github.com/TheoDfft/SCARA-Drawer
        # link_text: Project Website
        additional_links:
          - title:  TheoDfft/SCARA-Drawer
            # icon: fab fa-github
            # url: github.com/TheoDfft/hodor-projec
        description: | # this will include new lines to allow paragraphs

          <p>Developed an interactive SCARA robotic system that replicates user drawings in real-time, showcasing the integration of computer vision, embedded control, and robotics for human-guided tasks.</p>

          <ul style="list-style-type: disc; margin-left: 25px;">
            <li><b>Vision & Tracking:</b> Implemented <b>Raspberry Pi</b> camera system to track an <b>ArUco marker</b> on a stylus using <b>OpenCV</b> for real-time position detection</li>
            <li><b>Software Architecture:</b> Built on <b>ROS</b> framework for robust inter-process communication and system integration</li>
            <li><b>Motion Control:</b> Applied a <b>singularity robust inverse kinematics</b> algorithm with Jacobian and chain rule to translate tracked positions into precise robotic movements</li>
            <li><b>Hardware Integration:</b> Designed system around <b>Arduino</b> microcontroller and <b>Dynamixel servos</b> for accurate joint control</li>
            <li><b>End-Effector Design:</b> Created custom compliant drawing tool for consistent contact across various drawing surfaces</li>
          </ul><br>

          <div style="text-align: center; margin-bottom: 20px;">
            <!-- SCARA video -->
            <div style="margin-bottom: 20px;">
              <video autoplay loop muted playsinline style="height: 35%; border: 3px solid #555; border-radius: 5px; box-shadow: 0 4px 8px rgba(0,0,0,0.2);" id="scara-video">
                <source src="/images/scara_drawbot.mp4" type="video/mp4">
                Your browser does not support the video tag.
              </video>
            </div>
            
            <!-- RViz video centered -->
            <div style="margin-bottom: 20px;">
              <video autoplay loop muted playsinline style="width: 50%; border: 3px solid #555; border-radius: 5px; box-shadow: 0 4px 8px rgba(0,0,0,0.2);" id="rviz-video">
                <source src="/images/drawbot_rviz.mp4" type="video/mp4">
                Your browser does not support the video tag.
              </video>
            </div>
            
            <!-- CAD images in a row -->
            <div>
              <img src="/images/scara_drawbot_CAD.png" alt="SCARA Drawbot CAD" style="width: 40%; margin-right: 20px; display: inline-block; border: 3px solid; border-radius: 5px; box-shadow: 0 4px 8px rgba(0,0,0,0.2);">
              <img src="/images/end_effector_CAD.png" alt="SCARA end effector CAD" style="width: 40%; display: inline-block; border: 3px solid; border-radius: 5px; box-shadow: 0 4px 8px rgba(0,0,0,0.2);">
            </div>
            
            <script>
              document.getElementById('scara-video').playbackRate = 3.0;
              document.getElementById('rviz-video').playbackRate = 2.0;
            </script>
          </div>

          ___

      - layout: top-middle
        title: Hodor Project
        link: github.com/TheoDfft/hodor-project
        # link_text: Project Website
        additional_links:
          - title:  TheoDfft/hodor-project
            # icon: fab fa-github
            # url: github.com/TheoDfft/hodor-project
        description: | # this will include new lines to allow paragraphs
          <div style="overflow: auto; margin-bottom: 20px;">
            <img src="/images/phone_mockup.png" alt="Hodor mobile webpage" style="float: right; width: 35%; margin-left: 20px; border: 3px solid; border-radius: 5px; box-shadow: 0 4px 8px rgba(0,0,0,0.2);">
            
            <p>Engineered an advanced security system using the NVIDIA Jetson Nano, providing automated entrance monitoring and real-time facial recognition to enhance building security.</p>
            
            <ul style="list-style-type: disc; margin-left: 25px;">
              <li><b>Computer Vision:</b> Leveraged <b>OpenCV</b> for high-accuracy facial recognition, enabling reliable identification in various lighting conditions using <b>HOG</b> and <b>Face Landmarks Detection</b></li>
              <li><b>Web Development:</b> Created an interactive interface with <b>JavaScript</b>, <b>HTML</b>, and <b>CSS</b> for real-time user engagement and system management</li>
              <li><b>Backend Architecture:</b> Built with <b>Flask</b> to efficiently manage video streams and facial recognition processing</li>
              <li><b>Machine Learning:</b> Implemented facial recognition models with low false positives using trained face encodings</li>
              <li><b>System Integration:</b> Utilized <b>Python</b> for sophisticated backend logic, connecting various <b>IoT</b> components</li>
              <li><b>Data Management:</b> Employed <b>SQL</b> for robust historical data storage, enabling effective log tracking and queries</li>
              <li><b>API Integration:</b> Connected external services for instant push notifications upon face detection</li>
              <li><b>Energy Optimization:</b> Designed efficient motion detection based on pixel differentiation to conserve system resources</li>
            </ul>
          </div>
          
          <div style="text-align: center; margin-bottom: 20px;">
            <img src="/images/Hodor_webpage_main.png" alt="Hodor webpage" style="width: 70%; border: 3px solid; border-radius: 5px; box-shadow: 0 4px 8px rgba(0,0,0,0.2);">
          </div><br>
          
          ___
          

      - layout: top-middle
        title: Neurobiology Lab Testing Apparatus
        link: https://sites.google.com/eng.ucsd.edu/156b-2021-winter-team19/
        # link_text: Project Website
        additional_links:
          # - title:  TheoDfft/hodor-project
            # icon: fab fa-github
            # url: github.com/TheoDfft/hodor-project
            # image: images/profile_pic.jpeg
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        sub_title: >
          Leichtag Biomedical Research
        description: | # this will include new lines to allow paragraphs
          <p>Improved a cutting-edge cerebellar learning apparatus for neuroscientific research, enhancing precision and reliability of the experimental setup while optimizing the comfort of the test subjects.</p>
          
          <ul style="list-style-type: disc; margin-left: 25px;">
            <li><b>Software Development:</b> Integrated <b>MATLAB</b> and <b>C++</b> for sophisticated <b>computer vision</b> and <b>data processing</b> capabilities</li>
            <li><b>Embedded Systems:</b> Employed a <b>Teensy microcontroller</b> for millisecond-accurate control of stimuli delivery and response recording</li>
            <li><b>Hardware Integration:</b> Automated high-speed camera and LED operations for synchronized stimulus delivery and blink detection</li>
            <li><b>Mechanical Design:</b> Engineered precise air injector control and a custom wheel for improved comfort of test subjects using <b>CAD</b>, <b>FEA</b>, and <b>Stress/Strain testing</b></li>
            <li><b>Real-time Systems:</b> Created a robust architecture for time-critical experimental measurements and stimulus control</li>
          </ul><br>
          
          <div style="text-align: center; margin-bottom: 20px;">
            <img src="/images/CDL_rig_annotated.PNG" alt="CDL rig annotated" style="width: 45%; margin-right: 20px; display: inline-block; border: 3px solid; border-radius: 5px; box-shadow: 0 4px 8px rgba(0,0,0,0.2);">
            <img src="/images/CDL_eye_CV.jpg" alt="CDL CV on mice eye" style="width: 35%; display: inline-block; border: 3px solid; border-radius: 5px; box-shadow: 0 4px 8px rgba(0,0,0,0.2);">
          </div>
          
  - title: <b>Experience</b> # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Locus Robotics
        link: https://locusrobotics.com/
        link_text: locusrobotics.com
        sub_title: Robotics Deployment Engineer
        caption: August 2022 - January 2024
        #quote: > Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            <p>Led the deployment of 30+ fleets of autonomous collaborative robots in warehouse environments, ensuring successful integration, operation, and ongoing support for customers across the United States.</p>
            
            <ul style="list-style-type: disc; margin-left: 25px;">
              <li><b>Robotic Deployment:</b> Implemented <b>SLAM techniques</b> for map generation and <b>ROS tools</b> including RVIZ and launch file configuration for successful robot operation</li>
              <li><b>System Administration:</b> Leveraged <b>Linux command-line</b>, <b>SSH</b>, and <b>Python debugging tools</b> for remote system management and troubleshooting</li>
              <li><b>Warehouse Automation:</b> Applied knowledge of <b>WMS/OMS</b> platforms to integrate robotic systems with existing warehouse infrastructure</li>
              <li><b>Robot Programming:</b> Used custom IDE based on <b>Python</b>, <b>ROS</b>, and <b>Ubuntu OS</b> to develop <b>fleet management</b> features and <b>robot behaviors</b></li>
              <li><b>Communication Protocols:</b> Implemented <b>Modbus protocol</b> for inter-robot communication and utilized <b>MongoDB</b> for central server data management</li>
              <li><b>Customer Relations:</b> Provided on-site and remote <b>customer support</b>, maintaining transparent communication channels for effective troubleshooting</li>
              <li><b>Performance Optimization:</b> Collaborated with cross-functional teams to drive significant customer productivity increases of up to 3x</li>
            </ul><br>

      - layout: top
        description: | # this will include new lines to allow paragraph
          
          ___
          
            
      - layout: left
        title: 2Go Products
        link: https://www.2goproducts.com/
        link_text: 2goproducts.com
        sub_title: Mechanical Design Engineer
        caption: January 2021 - July 2022
        #quote: > Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            <p>Designed and developed mechanical components for both R&D and mass production, helping the company expand its product line while improving manufacturing processes.</p>
            
            <ul style="list-style-type: disc; margin-left: 25px;">
              <li><b>Mechanical Design:</b> Created 100+ parts using <b>Solidworks</b>, <b>AutoCAD</b>, <b>Inventor</b> and <b>Fusion360</b>, contributing to an <b>invention patent</b> (US-20230100608-A1)</li>
              <li><b>Manufacturing:</b> Applied <b>DFM principles</b> and implemented <b>injection molding</b> and <b>ultrasonic welding</b> techniques for mass production</li>
              <li><b>Testing & Validation:</b> Developed stress/strain testing rigs to evaluate product performance and durability</li>
              <li><b>Rapid Prototyping:</b> Fabricated hundreds of parts using <b>SLA</b>, <b>FDM</b>, <b>CNC</b> and various <b>hand tools</b> for iterative design testing</li>
              <li><b>Leadership:</b> Led development of a new product while supervising two engineers, gaining valuable <b>project management</b> experience</li>
              <li><b>Product Development:</b> Gained comprehensive exposure to the full <b>product design cycle</b> from concept to manufacturing</li>
            </ul><br>

  - title: <b>Education</b> # Title for the section
    layout: list # Type of content section (list/text)
    content:

      - layout: left
        title: New York University
        caption: September 2024 - December 2025
        sub_title: M.S. in Mechatronics and Robotics
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          <b><u>GPA:</u></b> 3.89

          <b><u>Coursework:</u></b><br>
              Vertically Integrated Project: Research on Self-Driving Robots (VSLAM Focused)<br>
              Foundations of Robotics<br>
              Mathematics for Robotics<br>
              Advanced Mechatronics<br>
              Reinforcement Learning and Optimal Control for Robotics<br>
              Robot Perception<br>
              High-Technology Entrepreneurship<br>
              Intellectual Property for Technology and Information Managers<br>

      - layout: top
        description: | # this will include new lines to allow paragraph
        
          ___
              
      - layout: left
        title: University of California, San Diego
        caption: September 2018 - March 2021
        sub_title: B.S. in Mechanical Engineering, Specialization in Robotics and Controls
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          <b><u>GPA:</u></b> 3.84 (Cum Laude Honors)
          
          <b><u>Coursework:</u></b><br>
              Embedded Systems and Robotics<br>
              Robotic Planning and Estimation<br>
              Signals, Systems and Linear Controls<br>
              MATLAB/Python Programming for Engineers<br>
              Intro to Autonomous Vehicles<br>
              Engineering Design (SolidWorks, Inventor, Fusion360 and AutoCad)<br>
              Computer-Aided Analysis & Design (ANSYS FEA, Numerical Methods, Optimization)<br>
              Statics, Dynamics, Kinematics and Vibrations of Solids<br>
              Fluid Mechanics, Heat Transfer, Thermodynamics<br>
              Business Project Management<br>
              Databases and MySQL

      - layout: top
        description: | # this will include new lines to allow paragraph
          
          ___
          

      - layout: left
        title: Stanford University / DeepLearning.AI
        caption: March 2024
        sub_title: Specialization Certificate in Machine Learning
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          <ul style="list-style-type: disc; margin-left: 25px;">
            <li><b>Supervised Machine Learning:</b> Regression and Classification techniques</li>
            <li><b>Advanced Learning Algorithms:</b> Neural networks and deep learning fundamentals</li>
            <li><b>Unsupervised Learning:</b> Clustering, dimensionality reduction, recommender systems</li>
            <li><b>Reinforcement Learning:</b> Decision processes and policy optimization techniques</li>
          </ul>

  - title: <b>A Little More About Me</b>
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in tech and robotics some of my other interests and hobbies are:
      - Surfing
      - Gaming
      - Soccer
      - Rugby


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
