# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Theo Duffaut
title: Robotics Engineer
email: duffaut.theo@gmail.com
phone: +1 925-282-0175
website: www.TheoDfft.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  TheoDfft
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile_pic.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Theo and I'm an aspiring robotics engineer. I'm passionate about new technologies, how they work and how to apply them to have an impact on the world. With a background in Mechanical Engineering, a specialization in Robotics and Machine Learning and two years of industry experience with AMR deployment, I'm looking for new opportunities to grow and learn.<br>
  
  Currently pursuing a M.S in Mechatronics and Robotics at New York University. Graduating in December 2025.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Hodor Project
        link: github.com/TheoDfft/hodor-project
        # link_text: Project Website
        additional_links:
          - title:  TheoDfft/hodor-project
            # icon: fab fa-github
            # url: github.com/TheoDfft/hodor-project
            image: images/profile_pic.jpeg
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        sub_title: >
          AI-powered Entrance Monitoring System.
        description: | # this will include new lines to allow paragraphs
          <br><img src="/images/phone_mockup.png" alt="Hodor mobile webpage" style="float: right; margin-left: 20px; width: 30%;">

          <b><u>IoT Security System with NVIDIA Jetson Nano:</u></b><br> Engineered an advanced security system using the NVIDIA Jetson Nano and a webcam, providing automated entrance monitoring and real-time facial recognition to enhance building security.<br>

          <b><u>Facial Recognition Powered by OpenCV:</u></b><br> Leveraged <mark>OpenCV</mark> for high-accuracy facial recognition, enabling the system to reliably identify individuals in various lighting conditions, demonstrating the application of <mark>computer vision</mark> technologies such as Histogram of Oriented Gradients and Face Landmarks Detection.<br>

          <b><u>Responsive Web Interface:</u></b><br> Developed an interactive web interface using <mark>JavaScript</mark>, <mark>HTML</mark>, and <mark>CSS</mark>, facilitating real-time user engagement, face management, and access to entry logs, showcasing understanding of modern <mark>web development</mark> technologies.<br>

          <b><u>Flask Server Backend:</u></b><br> Created a Flask-based backend architecture to manage video streams and facial recognition processing efficiently, illustrating experience in server-side programming and real-time web communication.<br><br>

          <b><u>Machine Learning for Facial Recognition:</u></b><br> Implemented a <mark>machine learning</mark> model to achieve accurate facial recognition with low false positives (trained on known faces' encodings), highlighting a foundation in machine learning technologies and their optimization for real-world applications.<br>

          <b><u>Backend Logic with Python:</u></b><br> Utilized <mark>Python</mark> for sophisticated backend logic, integrating various <mark>IoT</mark> components and managing data processing tasks, showcasing the versatile application of Python in complex system development.<br>

          <b><u>Data Management with SQL:</u></b><br> Employed <mark>SQL</mark> for robust historical data management, enabling effective data querying and log tracking, reflecting capabilities in database management and design.<br>

          <b><u>Real-Time Notifications via External APIs:</u></b><br> Integrated external APIs for instant push notifications upon face detection, emphasizing the use of <mark>API integration</mark> and real-time data processing to enhance user experience.<br>

          <b><u>Efficient Motion Detection:</u></b><br> Designed a motion detection mechanism to activate the system (based on absolute pixel differentiation), optimizing energy use while ensuring continuous monitoring, demonstrating innovative application of motion sensing technology for system efficiency.<br>

          <img src="/images/Hodor_webpage_main.png" alt="Hodor webpage" style="float: bottom; margin-right: 20px; width: 60%;"><br>

      - layout: top-middle
        title: Neurobiology Lab Testing Apparatus
        link: https://sites.google.com/eng.ucsd.edu/156b-2021-winter-team19/
        # link_text: Project Website
        additional_links:
          # - title:  TheoDfft/hodor-project
            # icon: fab fa-github
            # url: github.com/TheoDfft/hodor-project
            # image: images/profile_pic.jpeg
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        sub_title: >
          Leichtag Biomedical Research
        description: | # this will include new lines to allow paragraphs
          
          Improved a cutting-edge cerebellar learning apparatus, integrating <mark>MATLAB</mark> and <mark>C++</mark> for <mark>computer vision</mark> and <mark>data processing</mark>, enhancing neuroscientific research capabilities.<br><br>
          
          Employed a <mark>Teensy microcontroller</mark> for precise, millisecond-accurate control of stimuli delivery and response recording, showcasing functional programming skills.<br><br>
          
          Automated high-speed camera and LED operations for synchronized stimulus delivery and blink detection, demonstrating expertise in <mark>hardware integration</mark> and real-time <mark>system design</mark>.<br><br>
          
          Engineered a system for precise air injector control and a custom wheel for improved comfort of the mice (<mark>CAD</mark>, <mark>FEA</mark>, <mark>Stress/Strain testing</mark>), illustrating innovative solutions for experimental challenges in neuroscience.<br>
          
          <img src="/images/CDL_rig_annotated.PNG" alt="CDL rig annotated" style="float: bottom; margin-top: 20px; width: 40%;">
          <img src="/images/CDL_eye_CV.jpg" alt="CDL CV on mice eye" style="float: bottom; margin-top: 20px; width: 30%;">
          
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Locus Robotics
        link: https://locusrobotics.com/
        link_text: locusrobotics.com
        sub_title: Robotics Deployment Engineer
        caption: August 2022 - January 2024
        #quote: > Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Deployed and maintained Locus' AMR fleet at customer sites. Gained expertise in SLAM, Embedded Linux and robotic support with ROS.

            Developed deployment standards and tools for newly acquired robots. Programmed, tested and deployed brand new fleet management features (queueing, autonomous charging routine, custom warehouse workflow, etc) but also individual robots behaviors (navigation and path-planning algorithms, pickup/dropoff actuations, recovery mechanisms).


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of California, San Diego
        caption: 2018 - 2021
        sub_title: B.S. in Mechanical Engineering, Specialization in Robotics and Controls
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          <b><u>GPA:</u></b> 3.84 (Cum Laude Honors)
          
          <b><u>Coursework:</u></b><br>
              Embedded Systems and Robotics<br>
              Robotic Planning and Estimation<br>
              Signals, Systems and Linear Controls<br>
              MATLAB/Python Programming for Engineers<br>
              Intro to Autonomous Vehicles<br>
              Engineering Design (SolidWorks, Inventor, Fusion360 and AutoCad)<br>
              Computer-Aided Analysis & Design (ANSYS FEA, Numerical Methods, Optimization)<br>
              Statics, Dynamics, Kinematics and Vibrations of Solids<br>
              Fluid Mechanics, Heat Transfer, Thermodynamics<br>
              Business Project Management<br>
              Databases and MySQL

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in tech and robotics some of my other interests and hobbies are:
      - Surfing
      - Gaming
      - Soccer
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
